# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - run: rm /usr/bin/link
        shell: bash
      - uses: ilammy/msvc-dev-cmd@v1
      - run: which ninja.exe
        shell: bash
      - run: |
         echo "FORCE_SKIA_BUILD=1" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: powershell
      - name: Enable long path support for git checkouts
        run: |
          git config --system core.longpaths true
        shell: powershell
      - name: Move cargo home close to the target/$profile directory, so that relative paths from build to cargo source are without drive letter
        run: |
          echo "CARGO_HOME=${{ runner.workspace }}\target\c" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: powershell
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
#      - run: choco upgrade llvm
      - run: cargo build --verbose

